# .travis.yml for Travis CI Integration

language: php

php:
- 5.5

env:
- DB=mysql

before_script:
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS WebSite;" -uroot; fi

script: phpunit test

