# .travis.yml for Travis CI Integration

language: php

php:
- 5.3
- 5.4
- 5.5
- 5.6
- hhvm

matrix:
allow_failures:
- php: hhvm

env:
- DB=mysql

before_script:
- echo 'Installing composer dependencies now!'
- composer install
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS WebSite;" -uroot; fi

script: phpunit test

